import { ServiceSales } from '../components/service-sales';
import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ArrowRight, Inbox, UserRoundCheck, Send, CalendarCheck2, CheckCircle2 } from 'lucide-react';
export const Route = createFileRoute('/booking-lead-automation')({head:()=>({meta:[{title:'Booking Automation + Command Center | The Launch Era'},{name:'description',content:'Get a personalized cleaning Booking Page and private Command Center, with editable pricing, availability, estimates and follow-ups.'},{property:'og:title',content:'Booking Automation + Command Center | The Launch Era'},{property:'og:description',content:'A personalized Booking Page connected to your private Command Center, with schedule and price controls.'},{name:'twitter:card',content:'summary_large_image'}],links:[{rel:'canonical',href:'https://thelaunchera.com/booking-lead-automation'},{rel:'alternate',hrefLang:'en-US',href:'https://thelaunchera.com/booking-lead-automation'},{rel:'alternate',hrefLang:'es-US',href:'https://thelaunchera.com/es/booking-lead-automation/'},{rel:'alternate',hrefLang:'x-default',href:'https://thelaunchera.com/booking-lead-automation'}]}),component: Page});
const steps=[[Inbox,'Service','Your customer picks a service or requests a quote.'],[CalendarCheck2,'Available times','Your published availability shows open slots.'],[UserRoundCheck,'Request organized','The request reaches your private Command Center.'],[Send,'Next steps','Review the request and follow up from one place.']];
const SALE_END=new Date('2026-11-01T04:00:00Z').getTime();
function useBookingPrice(){const [sale,setSale]=useState(()=>Date.now()<SALE_END);useEffect(()=>{const sync=()=>setSale(Date.now()<SALE_END);sync();const id=window.setInterval(sync,30000);return()=>window.clearInterval(id)},[]);return sale?'$19.99':'$99';}
function Page(){const price=useBookingPrice();return <main style={{background:'#f5f8ff'}}><section className="container service-hero"><div className="eyebrow">BOOKING AUTOMATION + COMMAND CENTER</div><h1 className="editorial">A cleaning request comes in. Know what happens next.</h1><p>Stop piecing together requests from scattered messages. Your personalized Booking Page collects the details; your private Command Center keeps requests and follow-ups organized. You control services, prices, and available times.</p>{price==="$19.99"&&<div className="booking-hero-offer"><span className="booking-offer-tag">The Fall Refresh Offer</span><span className="booking-offer-price"><del>$99</del><strong>$19.99</strong></span><span className="booking-offer-deadline">Ends Oct 31</span></div>}<div className="service-hero-actions"><a className="cta-button service-cta" href="/service-checkout/?offer=booking-flow&lang=en">Get Started — {price} <ArrowRight/></a><a className="service-demo-link" href="/booking-demo/?lang=en">Get my personalized demo <ArrowRight/></a></div><div className="service-proof-strip" aria-label="Purchase details"><span>PERSONALIZED BOOKING PAGE</span><span>YOUR PRIVATE COMMAND CENTER</span><span>PRICES + AVAILABILITY IN YOUR HANDS</span></div><p className="muted">24-hour production starts once your intake and all required details are complete.</p></section>
<section className="container service-story"><div className="service-flow-card"><div className="eyebrow">HOW YOUR BOOKING PAGE AND COMMAND CENTER CONNECT</div><div className="interactive-flow">{steps.map(([Icon,title,copy],i)=><div className="interactive-step" key={String(title)}><div className="step-icon"><Icon/></div><div><span>0{i+1}</span><h3>{String(title)}</h3><p>{String(copy)}</p></div>{i<steps.length-1&&<ArrowRight className="step-arrow"/>}</div>)}</div></div>
<div className="service-benefit-grid"><article><CheckCircle2/><div><div className="eyebrow">PERSONALIZED BOOKING PAGE</div><h2 className="editorial">Get the details before you reply.</h2><p>Your brand, services, property details, optional add-ons, special quote requests, and available time slots in one mobile-friendly page.</p></div></article><article><CheckCircle2/><div><div className="eyebrow">YOUR PRIVATE COMMAND CENTER</div><h2 className="editorial">Change your rates without rebuilding.</h2><p>Edit Pricing &amp; Services, fixed rates, estimates, add-ons, and Availability whenever you need. New requests and lead statuses stay organized in your private workspace.</p></div></article><article><CheckCircle2/><div><div className="eyebrow">FOLLOW-UP AND CONTROL</div><h2 className="editorial">See which request needs a next step.</h2><p>Choose how your bookings work: fixed-price services can confirm automatically when enabled, while custom quotes and special requests stay ready for your review. Keep leads organized and conversations moving.</p></div></article></div>
<div className="service-endcap"><span>BOOKING PAGE</span><ArrowRight/><span>AVAILABLE SLOT</span><ArrowRight/><span>COMMAND CENTER</span><ArrowRight/><strong>BOOKINGS ORGANIZED ✓</strong><small>Your own booking system. Update services, prices, and availability from your Command Center.</small></div></section><section className="container service-story"><ServiceSales product="booking" lang="en"/></section></main>}