import { ServiceSales } from '../components/service-sales';
import { createFileRoute } from '@tanstack/react-router';
import { ArrowRight, CalendarDays, UsersRound, FileText, Receipt, Clock3, MapPinned, Calculator, Sparkles, Check, Plus } from 'lucide-react';
export const Route=createFileRoute('/cleaning-web-app')({head:()=>({meta:[{title:'Cleaning Business Management Web App | The Launch Era'},{name:'description',content:'Manage bookings, clients, quotes, jobs, invoices, team time, mileage and routes in one web app built for cleaning businesses.'},{property:'og:title',content:'Cleaning Web App | The Launch Era'},{property:'og:description',content:'Run day-to-day cleaning business operations from one browser-based workspace.'},{name:'twitter:card',content:'summary_large_image'}],links:[{rel:'canonical',href:'https://thelaunchera.com/cleaning-web-app'},{rel:'alternate',hrefLang:'en-US',href:'https://thelaunchera.com/cleaning-web-app'},{rel:'alternate',hrefLang:'es-US',href:'https://thelaunchera.com/es/cleaning-web-app/'},{rel:'alternate',hrefLang:'x-default',href:'https://thelaunchera.com/cleaning-web-app'}]}),component:Page});
function Page(){return <main style={{background:'#eef6ff'}}><section className="container service-hero"><div className="eyebrow">CLEANING WEB APP</div><h1 className="editorial">Your next cleaning job. Every detail in one place.</h1><p>The address is in a text. The quote is in a note. The invoice is still on your list. Bring clients, jobs, quotes, and invoices into one Cleaning App you can open from your phone.</p><div className="service-hero-actions"><a className="cta-button service-cta" href="https://app.thelaunchera.com/?entry=signup">Start Your Free Trial <ArrowRight/></a><a className="service-demo-link" href="/cleaning-app-demo/?lang=en">Explore the interactive preview <ArrowRight/></a></div><div className="service-proof-strip" aria-label="Trial details"><span>NO CARD REQUIRED</span><span>30 DAYS FREE</span><span>THEN $3.99/MONTH</span></div></section>
<section className="container service-story"><div className="app-preview-heading"><div className="eyebrow">ILLUSTRATIVE PRODUCT VIEW</div><p>This is a visual example, not a live account. Want to try the controls? <a href="/cleaning-app-demo/?lang=en">Open the interactive preview <ArrowRight/></a></p></div><div className="app-command-scene" aria-label="Illustrative Cleaning App workspace" role="img">
<div className="app-command-main"><div className="app-command-head"><div><small>THE LAUNCH ERA CLEANING WEB APP</small><strong>Good morning 👋</strong><p>Here’s what needs your attention today.</p></div><span>3 jobs today</span></div>
<div className="app-command-actions"><span className="fake-action"><Plus/> New job</span><span className="fake-action featured"><Calculator/> Pricing Calculator</span><span className="fake-action"><FileText/> New quote</span></div>
<div className="pricing-preview"><div className="pricing-title"><span><Calculator/> PRICING CALCULATOR</span><small>Estimate before you quote</small></div><div className="pricing-fields"><div><small>Service</small><strong>Recurring cleaning</strong></div><div><small>Property size</small><strong>2,000 sq ft</strong></div><div><small>Frequency</small><strong>Biweekly</strong></div></div><div className="pricing-total"><div><small>ESTIMATED PRICE</small><strong>$—</strong><span>Adjust using your business settings</span></div><span className="fake-action">Use in quote <ArrowRight/></span></div></div>
<div className="today-job"><div className="job-time"><span>10:30</span><small>AM</small></div><div><small>NEXT JOB</small><strong>Recurring Cleaning</strong><p><MapPinned/> Client details + route ready</p></div><span className="status booked">Scheduled</span></div></div>
<div className="app-command-side"><div className="app-side-title"><Sparkles/><div><small>ONE PLACE</small><strong>From estimate to paid.</strong></div></div>
<div className="app-life-cycle"><div><Calculator/><p><small>01</small><strong>Calculate</strong><span>Build an estimate</span></p><Check/></div><div><FileText/><p><small>02</small><strong>Quote</strong><span>Send the next step</span></p><ArrowRight/></div><div><CalendarDays/><p><small>03</small><strong>Schedule</strong><span>Put the job on the calendar</span></p><ArrowRight/></div><div><Receipt/><p><small>04</small><strong>Invoice</strong><span>Keep payment visible</span></p><Check/></div></div>
<div className="app-utility-grid"><span><UsersRound/> Clients + jobs</span><span><Clock3/> Team + time</span><span><MapPinned/> Routes</span><span><CalendarDays/> Calendar</span></div></div></div>
<div className="app-real-features"><article><CalendarDays/><div><small>BOOKINGS + CALENDAR</small><strong>See incoming and recurring work.</strong></div></article><article className="highlight"><Calculator/><div><small>PRICING CALCULATOR</small><strong>Estimate with your own pricing setup.</strong></div></article><article><UsersRound/><div><small>CLIENTS + JOBS</small><strong>Keep details and history together.</strong></div></article><article><FileText/><div><small>QUOTES + INVOICES</small><strong>Move from estimate to the next step.</strong></div></article><article><Clock3/><div><small>TEAM + TIME</small><strong>Track time and mileage.</strong></div></article><article><MapPinned/><div><small>ROUTES</small><strong>Make the next stop easier to find.</strong></div></article></div>
<div className="app-preview-bottom"><a className="service-demo-link" href="/cleaning-app-demo/?lang=en">Try an interactive sample workspace <ArrowRight/></a><small>No signup needed · Fictional clients and jobs</small></div><div className="service-endcap"><span>ESTIMATE</span><ArrowRight/><span>QUOTE</span><ArrowRight/><span>SCHEDULE</span><ArrowRight/><span>JOB</span><ArrowRight/><strong>INVOICE ✓</strong><small>Web app · No App Store required · 30 days free · then $3.99/month.</small></div><ServiceSales product="app" lang="en"/></section></main>}