import { createFileRoute } from '@tanstack/react-router';
import { ArrowRight, CalendarDays, UsersRound, FileText, Receipt, Clock3, MapPinned, Calculator, Sparkles, Check, Plus } from 'lucide-react';
export const Route=createFileRoute('/cleaning-web-app')({component:Page});
function Page(){return <main style={{background:'#eef6ff'}}><section className="container service-hero"><div className="eyebrow">CLEANING WEB APP</div><h1 className="editorial">Run the day-to-day without piecing it together.</h1><p>Bookings, clients, pricing, quotes, jobs, invoices, team time, and routes—organized in one web app built around a cleaning business.</p><a className="cta-button service-cta" href="https://app.thelaunchera.com/">Start Your Free Trial <ArrowRight/></a></section>
<section className="container service-story"><div className="app-command-scene">
<div className="app-command-main"><div className="app-command-head"><div><small>THE LAUNCH ERA CLEANING APP</small><strong>Good morning 👋</strong><p>Here’s what needs your attention today.</p></div><span>3 jobs today</span></div>
<div className="app-command-actions"><button><Plus/> New job</button><button className="featured"><Calculator/> Pricing Calculator</button><button><FileText/> New quote</button></div>
<div className="pricing-preview"><div className="pricing-title"><span><Calculator/> PRICING CALCULATOR</span><small>Estimate before you quote</small></div><div className="pricing-fields"><div><small>Cleaning type</small><strong>Residential</strong></div><div><small>Home size</small><strong>2,000 sq ft</strong></div><div><small>Frequency</small><strong>Biweekly</strong></div></div><div className="pricing-total"><div><small>ESTIMATED PRICE</small><strong>$—</strong><span>Adjust using your business settings</span></div><button>Use in quote <ArrowRight/></button></div></div>
<div className="today-job"><div className="job-time"><span>10:30</span><small>AM</small></div><div><small>NEXT JOB</small><strong>Recurring Cleaning</strong><p><MapPinned/> Client details + route ready</p></div><span className="status booked">Scheduled</span></div></div>
<div className="app-command-side"><div className="app-side-title"><Sparkles/><div><small>ONE PLACE</small><strong>From estimate to paid.</strong></div></div>
<div className="app-life-cycle"><div><Calculator/><p><small>01</small><strong>Calculate</strong><span>Build an estimate</span></p><Check/></div><div><FileText/><p><small>02</small><strong>Quote</strong><span>Send the next step</span></p><ArrowRight/></div><div><CalendarDays/><p><small>03</small><strong>Schedule</strong><span>Put the job on the calendar</span></p><ArrowRight/></div><div><Receipt/><p><small>04</small><strong>Invoice</strong><span>Keep payment visible</span></p><Check/></div></div>
<div className="app-utility-grid"><span><UsersRound/> Clients + jobs</span><span><Clock3/> Team + time</span><span><MapPinned/> Routes</span><span><CalendarDays/> Calendar</span></div></div></div>
<div className="app-real-features"><article><CalendarDays/><div><small>BOOKINGS + CALENDAR</small><strong>See incoming and recurring work.</strong></div></article><article className="highlight"><Calculator/><div><small>PRICING CALCULATOR</small><strong>Estimate with your own pricing setup.</strong></div></article><article><UsersRound/><div><small>CLIENTS + JOBS</small><strong>Keep details and history together.</strong></div></article><article><FileText/><div><small>QUOTES + INVOICES</small><strong>Move from estimate to the next step.</strong></div></article><article><Clock3/><div><small>TEAM + TIME</small><strong>Track time and mileage.</strong></div></article><article><MapPinned/><div><small>ROUTES</small><strong>Make the next stop easier to find.</strong></div></article></div>
<div className="service-endcap"><span>ESTIMATE</span><ArrowRight/><span>QUOTE</span><ArrowRight/><span>SCHEDULE</span><ArrowRight/><span>JOB</span><ArrowRight/><strong>INVOICE ✓</strong><small>Web app · No App Store required · 30 days free when started on its own · 60 days included with Booking + Lead Automation · then $5.99/month.</small></div></section></main>}