import { createFileRoute } from '@tanstack/react-router';
import { useState, type FormEvent } from 'react';
import { ArrowRight, ArrowUpRight, Bell, CalendarCheck2, Check, CircleCheck, ClipboardList, MessageCircle, MessagesSquare, Send, Sparkles, Timer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import cleaner from '@/assets/cleaner-home.jpg';
import webapp from '@/assets/webapp-phone.jpg';
import website from '@/assets/website-workspace.jpg';
import assistant from '@/assets/assistant-workspace.jpg';
export const Route=createFileRoute('/es')({head:()=>({meta:[{title:'THE LAUNCH ERA — Tu cliente está listo para reservar.'},{name:'description',content:'Sistemas más simples para dueñas de negocios de limpieza residencial en EE. UU.'}]}),component:SpanishHome});
const services=[
 {title:'Booking + Lead Automation',landing:'/es/booking-lead-automation/',description:'De la primera consulta al seguimiento, sin perder el hilo.',image:cleaner,tag:'TU FLUJO DE RESERVAS, CONECTADO'},
 {title:'Cleaning Web App',landing:'/es/cleaning-web-app/',description:'Tu agenda, clientes y trabajo diario, más fácil de ver.',image:webapp,tag:'TU NEGOCIO, EN UN SOLO LUGAR'},
 {title:'Website Automation',landing:'/es/website-automation/',description:'Tu website recibe la consulta. El sistema mueve lo que sigue.',image:website,tag:'MENOS PASOS MANUALES'},
 {title:'Virtual Assistant',landing:'/es/virtual-assistant/',description:'Apoyo detrás de escena para que no todo dependa de ti.',image:assistant,tag:'MÁS APOYO. MENOS CARGA'}];
const notices=[['Nueva solicitud de reserva','Una nueva oportunidad para tu negocio.',CalendarCheck2],['Nuevo lead guardado','Ya está organizado en tu Lead Tracker.',ClipboardList],['Seguimiento enviado','El próximo paso ya va en camino.',Send],['Cliente reservado','Una cosa menos en tu lista.',CircleCheck]] as const;
const flow=[['NUEVO LEAD','Llega una solicitud de reserva.','Los detalles entran en un solo lugar.',CalendarCheck2],['ORGANIZADO','Se guarda en tu Lead Tracker.','Cada consulta tiene su lugar. Sin buscar entre mensajes.',ClipboardList],['SEGUIMIENTO','El próximo paso sigue avanzando.','Un seguimiento claro mantiene la conversación viva.',Send]] as const;
function SpanishContact(){
 const [status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle'); const [name,setName]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('sending');const fd=new FormData(e.currentTarget);try{const r=await fetch('https://bowacxhmjvrqixtwaikv.supabase.co/functions/v1/tle-contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:String(fd.get('name')||''),email:String(fd.get('email')||''),business_name:String(fd.get('business')||''),help_needed:[String(fd.get('service')||'')],message:String(fd.get('message')||''),language:'es',source:'main_website_es',started_at:Date.now()-3000,website:''})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw 0;setStatus('sent')}catch{setStatus('error')}}
 return <div className="contact-form">{status==='sent'?<div className="form-confirm"><Sparkles/><h3 className="editorial">Gracias, {name.split(' ')[0]}.</h3><p>Ya recibimos tu consulta. La revisaremos y te escribiremos pronto.</p><Button variant="outline" onClick={()=>setStatus('idle')}>Enviar otra consulta <ArrowRight/></Button></div>:<><h2 className="editorial">Cuéntanos un poquito de tu negocio.</h2><p>No necesitas tener todo resuelto. Solo dinos qué se está sintiendo pesado ahora mismo.</p><form onSubmit={submit}><div className="form-grid"><label className="field">Tu nombre<input name="name" required value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre y apellido"/></label><label className="field">Correo electrónico<input name="email" type="email" required placeholder="Donde podamos contactarte"/></label></div><label className="field">Nombre del negocio<input name="business" required placeholder="Tu negocio de limpieza"/></label><label className="field">¿Con qué te gustaría recibir ayuda?<select name="service">{services.map(s=><option key={s.title}>{s.title}</option>)}<option>No estoy segura todavía</option></select></label><label className="field">¿Qué te está quitando demasiado tiempo?<textarea name="message" required placeholder="Cuéntanos qué pasa en tu día a día…"/></label>{status==='error'&&<p className="text-sm">No pudimos enviarlo. Inténtalo otra vez.</p>}<Button type="submit" variant="editorial" className="cta-button" disabled={status==='sending'}>{status==='sending'?'Enviando…':'Enviar mi consulta'} <ArrowRight/></Button><p className="form-disclaimer">Tu consulta llega directamente a The Launch Era. Usaremos estos datos solo para responderte.</p></form></>}</div>
}
function SpanishHome(){const [active,setActive]=useState(0);return <main>
<section className="hero-photo"><img src={cleaner} alt="Profesional de limpieza trabajando en una casa moderna"/><span className="photo-label">TÚ CUIDAS LOS HOGARES. NOSOTROS CUIDAMOS LO QUE SIGUE.</span>{notices.map(([title,text,Icon],i)=><div className={`notification notice-${i+1}`} key={title}><span className="notice-icon"><Icon size={19}/></span><div><small><span>THE LAUNCH ERA</span><span>ahora</span></small><strong>{title}</strong><p>{text}</p></div></div>)}</section>
<section className="hero-copy"><div className="eyebrow">MENOS PERSEGUIR. MÁS CLARIDAD. MÁS ESPACIO PARA TU NEGOCIO.</div><h1>TU CLIENTE ESTÁ LISTO PARA RESERVAR.</h1><p className="hero-accent editorial">Tu sistema también debería estarlo.</p><div className="lead-flow">{flow.map(([title,text,detail,Icon],i)=><div className={`flow-step ${i===active?'active':''}`} key={title}><Button variant="circle" className="flow-circle" onClick={()=>setActive(i)}><Icon/></Button><h3><span>0{i+1}</span>{title}</h3><p>{text}</p></div>)}</div><p className="flow-detail">{flow[active][2]}</p><Button variant="editorial" className="cta-button" asChild><a href="#soluciones">Ver la solución <ArrowRight/></a></Button></section>
<section id="soluciones" className="solutions-section"><div className="container"><div className="section-heading"><div className="eyebrow">SISTEMAS QUE HACEN MÁS LIGERO EL DÍA A DÍA.</div><h2 className="editorial">Lo que pasa después<br/>de que alguien quiere reservar</h2><p>No necesitas otra lista de pendientes. Necesitas que las cosas tengan un lugar y un próximo paso.</p></div><div className="service-grid">{services.map((s,i)=><a className="service-card" href={s.landing} key={s.title} onClick={(e)=>{e.preventDefault();window.location.assign(s.landing)}}><div className="service-image"><img src={s.image} alt=""/><span className="service-number">0{i+1}</span><span className="service-arrow"><ArrowUpRight size={18}/></span></div><h3>{s.title}</h3><p>{s.description}</p><div className="card-tag">{s.tag}</div></a>)}</div></div></section>
<section className="problem-section"><div className="container problem-layout"><div><div className="eyebrow">NO DEBERÍAS TERMINAR EL DÍA BUSCANDO MENSAJES.</div><h2 className="editorial">Tu negocio crece.<br/><em>La parte de atrás también.</em></h2><p className="problem-intro">Entre clientes, casas, equipo y mensajes, es fácil que lo administrativo termine ocupando más espacio del que debería.</p></div><div><div className="pain-item"><MessagesSquare/><div><h3>“Sé que me escribió… ¿pero dónde?”</h3><p>Texto, DM, email. Una consulta buena no debería perderse entre pestañas.</p></div></div><div className="pain-item"><Bell/><div><h3>“Tenía que responderle ayer.”</h3><p>Un día ocupado no debería convertirse en una reserva perdida.</p></div></div><div className="pain-item"><Timer/><div><h3>“Todavía estoy con admin a esta hora.”</h3><p>Cuando todo depende de ti, el trabajo se sigue alargando.</p></div></div><p className="problem-bottom">No se trata de hacer más. Se trata de tener un flujo más claro.</p></div></div></section>
<section className="booking-section"><div className="container booking-layout"><div className="booking-copy"><div className="eyebrow">BOOKING + LEAD AUTOMATION</div><h2 className="editorial">De “me interesa”<br/>a <em>“ya quedó reservado.”</em></h2><p className="description">Un solo flujo para solicitudes, datos del cliente y seguimientos. Así cada lead sabe qué sigue, aunque tú estés ocupada.</p><ul className="check-list"><li><Check/>Solicitudes en un solo lugar</li><li><Check/>Datos del lead organizados</li><li><Check/>Seguimientos que mantienen el movimiento</li><li><Check/>Una vista clara de quién está listo para reservar</li></ul><Button variant="editorial" className="cta-button" asChild><a href="/es/booking-lead-automation/">Conoce tu nuevo flujo <ArrowRight/></a></Button></div><div className="tracker-scene"><div className="tracker"><div className="tracker-title"><h3>Tu Lead Tracker</h3><small>Todo al día</small></div><p className="tracker-subtitle">Un lugar para cada consulta. Un próximo paso para cada lead.</p><div className="tracker-stats"><div><strong>12</strong><span>Nuevas consultas</span></div><div><strong>8</strong><span>Seguimientos</span></div><div><strong>6</strong><span>Reservados</span></div></div><div className="tracker-row header"><span>CLIENTE</span><span>SERVICIO</span><span>ESTADO</span></div><div className="tracker-row"><strong>Sarah M.<small>Website</small></strong><span>Recurring</span><span className="status booked">Reservada ✓</span></div><div className="tracker-row"><strong>Jessica R.<small>Formulario</small></strong><span>Deep clean</span><span className="status followup">Follow-up</span></div><div className="tracker-row"><strong>Amanda K.<small>Mensaje</small></strong><span>Move-out</span><span className="status">Nuevo lead</span></div></div></div></div></section>
<section className="process-section"><div className="container"><div className="section-heading"><div className="eyebrow">EMPEZAR ES SIMPLE.</div><h2 className="editorial">Un flujo más claro, en tres pasos.</h2></div><div className="process-grid"><div className="process-step"><div className="process-number">01</div><h3>Cuéntanos qué se está sintiendo pesado.</h3><p>Vemos cómo trabajas hoy y dónde se te está yendo el tiempo.</p></div><div className="process-step"><div className="process-number">02</div><h3>Conectamos lo que hace falta.</h3><p>Armamos el sistema alrededor de tu negocio, no al revés.</p></div><div className="process-step"><div className="process-number">03</div><h3>Tu día empieza a sentirse más ligero.</h3><p>Te mostramos el flujo para que sepas exactamente cómo usarlo.</p></div></div></div></section>
<section className="final-section"><div className="eyebrow">TU PRÓXIMA ERA PUEDE SENTIRSE MÁS LIGERA.</div><h2 className="editorial">Menos cosas regadas.<br/><em>Más claridad para seguir creciendo.</em></h2><p>Cuéntanos qué te está quitando tiempo y vemos cuál es el próximo paso que realmente te ayudaría.</p><Button variant="editorial" className="cta-button" asChild><a href="#contacto"><MessageCircle/> Hablemos de tu negocio <ArrowUpRight/></a></Button><div className="final-note">Una consulta sencilla. Una conversación humana. Sin presión.</div></section>
<section id="contacto" className="container help-layout" style={{paddingTop:'70px'}}><div className="faq-list"><h2 className="editorial">Antes de empezar, un poquito de claridad.</h2><details><summary>¿Esto es para un negocio como el mío?</summary><p>Está pensado para dueñas de negocios de limpieza residencial en EE. UU., desde quien todavía maneja sus consultas sola hasta quien ya tiene equipo.</p></details><details><summary>¿Tengo que cambiar las herramientas que ya uso?</summary><p>No necesariamente. Primero vemos lo que ya tienes y qué realmente vale la pena conectar o simplificar.</p></details><details><summary>¿Pueden ayudarme con algo más que reservas?</summary><p>Sí. También tenemos Cleaning Web App, Website Automation y Virtual Assistant Support.</p></details><details><summary>¿Cuánto cuesta?</summary><p>Cada servicio muestra su precio antes del checkout para que sepas exactamente qué estás eligiendo.</p></details></div><SpanishContact/></section>
</main>}