import { createFileRoute } from '@tanstack/react-router';
import cleaner from '@/assets/cleaner-home.jpg';
import webapp from '@/assets/webapp-phone.jpg';
import website from '@/assets/website-workspace.jpg';
import assistant from '@/assets/assistant-workspace.jpg';
import { ArrowRight, CalendarCheck2, ClipboardList, Send, CircleCheck } from 'lucide-react';
export const Route=createFileRoute('/es')({head:()=>({meta:[{title:'THE LAUNCH ERA — Tu cliente está listo para reservar.'},{name:'description',content:'Automatización de reservas y leads y apoyo para dueñas de negocios de limpieza residencial en EE. UU.'}]}),component:SpanishHome});
const services=[
['Booking + Lead Automation','Desde la primera consulta hasta el próximo seguimiento. Nada se pierde.',cleaner,'/booking-lead-automation','TU FLUJO DE RESERVAS, CONECTADO'],
['Cleaning Web App','Tu negocio del día a día, en un solo lugar. Directamente desde tu teléfono.',webapp,'/cleaning-web-app','TODO EN UN SOLO LUGAR'],
['Website Automation','Una primera impresión hermosa. Un camino claro para reservar.',website,'/website-automation','MÁS QUE UN WEBSITE BONITO'],
['Virtual Assistant','Apoyo atento detrás de escena para tus días más ocupados.',assistant,'/virtual-assistant','UN POCO DE AYUDA CAMBIA MUCHO']];
function SpanishHome(){return <main>
<section className="hero-photo"><img src={cleaner} alt="Profesional de limpieza trabajando en una casa moderna" width={1920} height={1024}/><span className="photo-label">TÚ CUIDAS LOS HOGARES. NOSOTROS CUIDAMOS LO QUE SIGUE.</span><div className="notification notice-1"><span className="notice-icon"><CalendarCheck2 size={19}/></span><div><small><span>THE LAUNCH ERA</span><span>ahora</span></small><strong>Nueva solicitud de reserva</strong><p>Una nueva oportunidad para tu negocio.</p></div></div><div className="notification notice-2"><span className="notice-icon"><ClipboardList size={19}/></span><div><small><span>THE LAUNCH ERA</span><span>ahora</span></small><strong>Nuevo lead guardado</strong><p>Organizado en tu Lead Tracker.</p></div></div></section>
<section className="hero-copy"><div className="eyebrow">MENOS PERSEGUIR. MÁS RESERVAS. MÁS TRANQUILIDAD.</div><h1>TU CLIENTE ESTÁ LISTO PARA RESERVAR.</h1><p className="hero-accent editorial">Tu sistema también debería estarlo.</p><a className="cta-button inline-flex items-center justify-center" href="#soluciones">Ver la solución <ArrowRight/></a></section>
<section id="soluciones" className="solutions-section"><div className="container"><div className="section-heading"><div className="eyebrow">SISTEMAS PENSADOS PARA TU NEGOCIO</div><h2 className="editorial">Todo lo que pasa<br/>después de que hacen clic en Reservar</h2><p>Estás construyendo un negocio, no una lista interminable de pendientes. Hagamos que la parte de atrás se sienta más ligera.</p></div><div className="service-grid">{services.map((s,i)=><a className="service-card" href={s[3] as string} key={s[0] as string}><div className="service-image"><img src={s[2] as string} alt="" width={1024} height={1024}/><span className="service-number">0{i+1}</span></div><h3>{s[0]}</h3><p>{s[1]}</p><div className="card-tag">{s[4]}</div></a>)}</div></div></section>
<section className="problem-section"><div className="container problem-layout"><div><div className="eyebrow">NO EMPEZASTE UN NEGOCIO PARA PERSEGUIR MENSAJES.</div><h2 className="editorial">Excelente limpiando.<br/>¿Enterrada en <em>todo lo demás?</em></h2><p className="problem-intro">Tienes casas que limpiar, un equipo que manejar y clientes que atender. La administración no debería seguirte hasta tu casa.</p></div><div><div className="pain-item"><Send/><div><h3>“Sé que me escribió por algún lado…”</h3><p>Textos, DMs y emails. Los buenos leads se pierden entre tantas pestañas.</p></div></div><div className="pain-item"><CircleCheck/><div><h3>“Ayer tenía que darle seguimiento.”</h3><p>Los días ocupados se convierten en respuestas y reservas perdidas.</p></div></div></div></div></section>
<section className="booking-section"><div className="container booking-layout"><div className="booking-copy"><div className="eyebrow">BOOKING + LEAD AUTOMATION</div><h2 className="editorial">De “me interesa”<br/>a <em>“ya estás reservada.”</em></h2><p className="description">Un flujo conectado para solicitudes, información del cliente y seguimientos, incluso cuando estás ocupada.</p><a className="cta-button inline-flex items-center justify-center" href="/booking-lead-automation">Conoce tu nuevo flujo <ArrowRight/></a></div></div></section>
<section className="process-section"><div className="container"><div className="section-heading"><div className="eyebrow">FÁCIL DE EMPEZAR. CREADO ALREDEDOR DE TI.</div><h2 className="editorial">Un mejor flujo, en tres pasos.</h2></div><div className="process-grid"><div className="process-step"><div className="process-number">01</div><h3>Cuéntanos qué se está complicando.</h3><p>Conocemos tu negocio y qué te está quitando demasiado tiempo.</p></div><div className="process-step"><div className="process-number">02</div><h3>Conectamos los puntos.</h3><p>Creamos un sistema pensado alrededor de cómo trabajas.</p></div><div className="process-step"><div className="process-number">03</div><h3>Recuperas tu tiempo.</h3><p>Te mostramos tu nuevo flujo para que puedas usarlo con confianza.</p></div></div></div></section>
<section className="final-section"><div className="eyebrow">TU PRÓXIMA ERA EMPIEZA AQUÍ.</div><h2 className="editorial">Un negocio que funciona mejor.<br/><em>Un día que se siente más ligero.</em></h2><p>Quitamos de tu plato las partes desorganizadas y repetitivas para dejar espacio para lo que sigue.</p><a className="cta-button inline-flex items-center justify-center" href="/help?lang=es">Hablemos de tu negocio <ArrowRight/></a></section>
</main>}
