import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, Bell, CalendarCheck2, Check, CircleCheck, ClipboardList, MessageCircle, MessagesSquare, Send, Sparkles, Timer, Workflow } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import cleaner from '@/assets/cleaner-home.jpg';
import webapp from '@/assets/webapp-phone.jpg';
import website from '@/assets/website-workspace.jpg';
import assistant from '@/assets/assistant-workspace.jpg';

export function Wave({foam=false}:{foam?:boolean}) { return foam ? <div className="foam-wave" aria-hidden="true"><svg viewBox="0 0 1440 110" preserveAspectRatio="none"><path d="M0 48C50 48 52 10 112 17C151 20 166 48 207 46C255 45 261 22 301 25C348 29 346 64 399 63C448 63 459 42 505 44C548 46 555 73 605 70C675 66 686 18 750 23C805 27 807 63 858 60C911 58 918 35 969 38C1020 41 1024 70 1071 68C1116 66 1132 28 1185 33C1232 37 1237 63 1288 61C1344 59 1370 32 1440 40V110H0Z"/></svg></div> : <svg className="soft-wave" viewBox="0 0 1440 70" preserveAspectRatio="none" aria-hidden="true"><path d="M0 41C220 2 290 72 510 43C730 13 790 2 980 28C1170 56 1270 7 1440 35V70H0Z"/></svg> }
const notifications = [{title:'New Booking Request',text:'A fresh start for a sparkling home.',icon:CalendarCheck2},{title:'New Lead Added',text:'Safely saved to your Lead Tracker.',icon:ClipboardList},{title:'Follow-Up Sent',text:'The right message. Right on time.',icon:Send},{title:'Client Booked',text:'One less thing on your to-do list.',icon:CircleCheck}];
const flow = [{title:'NEW LEAD',text:'Booking request comes in.',detail:'Your booking form captures the details, all in one place.',icon:CalendarCheck2},{title:'TRACKED',text:'Added to the Lead Tracker automatically.',detail:'Every inquiry has a home. No more searching through messages.',icon:ClipboardList},{title:'FOLLOWED UP',text:'The next step keeps moving.',detail:'A thoughtful follow-up keeps the conversation going.',icon:Send}];
export function HomeHero() {
 const [active,setActive]=useState(0);
 return <><section className="hero-photo" aria-label="Your cleaning business, with a little more breathing room"><img src={cleaner} alt="A professional cleaner carefully wiping a console in a bright modern home" width={1920} height={1024} fetchPriority="high"/><span className="photo-label">YOU TAKE CARE OF THE HOMES. WE TAKE CARE OF WHAT’S NEXT.</span>{notifications.map((n,i)=><div className={`notification notice-${i+1}`} key={n.title}><span className="notice-icon"><n.icon size={19}/></span><div><small><span>THE LAUNCH ERA</span><span>now</span></small><strong>{n.title}</strong><p>{n.text}</p></div></div>)}<Wave foam/></section><section className="hero-copy"><div className="eyebrow">LESS CHASING. MORE BOOKING. MORE BREATHING ROOM.</div><h1>YOUR CLIENT IS READY TO BOOK.</h1><p className="hero-accent editorial">Your system should be too.</p><div className="lead-flow">{flow.map((s,i)=><div className={`flow-step ${i===active?'active':''}`} key={s.title}><Button variant="circle" className="flow-circle" aria-label={`Step ${i+1}: ${s.title}`} aria-pressed={i===active} onClick={()=>setActive(i)}><s.icon/></Button><h3><span>0{i+1}</span>{s.title}</h3><p>{s.text}</p></div>)}</div><p className="flow-detail" aria-live="polite">{flow[active]?.detail}</p><Button variant="editorial" className="cta-button" asChild><a href="#booking-lead-automation">See the Solution <ArrowRight/></a></Button></section></>;
}
const services = [
 {title:'Booking + Lead Automation',landing:'https://thelaunchera.com/start/',description:'From the first inquiry to the next follow-up. Nothing slips through.',image:cleaner,alt:'Cleaner working in a bright residential home',tag:'YOUR BOOKING FLOW, CONNECTED',points:['A booking form that captures the right details','An organized Lead Tracker','Timely follow-ups and clear next steps'],checkout:'https://thelaunchera.com/pay/booking-flow/'},
 {title:'Cleaning Web App',landing:'https://thelaunchera.com/cleaning-app/',description:'Your day-to-day business, in one place. Right from your phone.',image:webapp,alt:'A phone showing a softly blurred cleaning business management app on a bright desk',tag:'ONE PLACE FOR THE DAY TO DAY',points:['Calendar and jobs at a glance','Clients, quotes, and invoices together','Team and workflow, organized','Time and mileage, kept simple'],checkout:null},
 {title:'Website Automation',landing:'https://thelaunchera.com/automation/',description:'A beautiful first impression. A clear path to book.',image:website,alt:'A laptop showing a cleaning business website',tag:'MORE THAN A PRETTY WEBSITE',points:['A clear, welcoming online home','Connected inquiry and booking forms','An easier next step for potential clients'],checkout:'https://thelaunchera.com/service-checkout/?offer=website-automation&lang=en'},
 {title:'Virtual Assistant',landing:'https://thelaunchera.com/virtual-assistant/',description:'Thoughtful, behind-the-scenes support for your busy days.',image:assistant,alt:'A virtual assistant working at a laptop in her home office',tag:'A LITTLE HELP GOES A LONG WAY',points:['Help with your everyday admin','A more organized inbox and client information','Support shaped around your business'],checkout:'https://thelaunchera.com/service-checkout/?offer=va&lang=en'}
];
export function SolutionsSection() {
 const [selected,setSelected]=useState<number|null>(null);
 const service = selected===null ? null:services[selected];
 return <section className="solutions-section"><Wave/><div className="container"><div className="section-heading"><div className="eyebrow">THOUGHTFUL SYSTEMS. REAL-LIFE RELIEF.</div><h2 className="editorial">Everything that happens<br/>after they click Book</h2><p>You’re building a business, not a never-ending to-do list.<br className="hidden sm:block"/> Let’s make the behind-the-scenes feel a little lighter.</p></div><div className="service-grid">{services.map((s,i)=><a className="service-card" key={s.title} href={s.landing}><ServiceCard service={s} index={i}/></a>)}</div></div><Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="service-modal max-h-[90dvh] overflow-auto">{service&&<><img className="service-modal-img" src={service.image} alt={service.alt} width={1024} height={1024}/><DialogTitle>{service.title}</DialogTitle><DialogDescription>{service.description}</DialogDescription><ul className="check-list">{service.points.map(p=><li key={p}><Check/>{p}</li>)}</ul>{service.checkout?<Button variant="editorial" className="cta-button" asChild><a href={service.checkout}>Get Started <ArrowRight/></a></Button>:<Button variant="editorial" className="cta-button" asChild><Link to="/help" onClick={()=>setSelected(null)}>Let’s talk about your business <ArrowRight/></Link></Button>}</>}</DialogContent></Dialog></section>;
}
function ServiceCard({service:s,index:i}:{service:typeof services[number],index:number}) { return <><div className="service-image"><img src={s.image} alt={s.alt} loading="lazy" width={1024} height={1024}/><span className="service-number">0{i+1}</span><span className="service-arrow"><ArrowUpRight size={18}/></span></div><h3>{s.title}</h3><p>{s.description}</p><div className="card-tag">{s.tag}</div></> }
export function ProblemSection() { return <section className="problem-section"><div className="container problem-layout"><div><div className="eyebrow">YOU DIDN’T START A BUSINESS TO CHASE MESSAGES.</div><h2 className="editorial">Great at cleaning.<br/>Buried in <em>everything else?</em></h2><p className="problem-intro">You’ve got homes to clean, a team to manage, and clients to care for. The admin shouldn’t follow you home.</p></div><div><div className="pain-item"><MessagesSquare/><div><h3>“I know they messaged me somewhere…”</h3><p>Texts, DMs, emails. Good leads get lost between all the tabs.</p></div></div><div className="pain-item"><Bell/><div><h3>“I meant to follow up yesterday.”</h3><p>Busy days turn into missed replies and missed bookings.</p></div></div><div className="pain-item"><Timer/><div><h3>“I’m still doing admin at 9 p.m.”</h3><p>Scattered details and manual updates steal your time back.</p></div></div><p className="problem-bottom">It’s not that you need to work harder. You need a better flow.</p></div></div></section> }
export function LeadTracker() { return <div><div className="tracker-scene"><div className="tracker"><div className="tracker-title"><h3>Your Lead Tracker</h3><small>All caught up</small></div><p className="tracker-subtitle">A place for every inquiry. A next step for every lead.</p><div className="tracker-stats"><div><strong>12</strong><span>New inquiries</span></div><div><strong>8</strong><span>Followed up</span></div><div><strong>6</strong><span>Clients booked</span></div></div><div className="tracker-row header"><span>CLIENT</span><span>SERVICE</span><span>STATUS</span></div><div className="tracker-row"><strong>Sarah M.<small>Website inquiry</small></strong><span>Recurring clean</span><span className="status booked">Booked ✓</span></div><div className="tracker-row"><strong>Jessica R.<small>Booking form</small></strong><span>Deep clean</span><span className="status followup">Follow-up sent</span></div><div className="tracker-row"><strong>Amanda K.<small>Direct message</small></strong><span>Move-out clean</span><span className="status">New lead</span></div></div><div className="tracker-note"><CircleCheck size={23}/><div><strong>Follow-up? Already handled.</strong><p>The next step is right on time.</p></div></div></div><p className="tracker-caption">AN ILLUSTRATIVE LOOK AT A MORE ORGANIZED DAY.</p></div> }
export function BookingSection({detail=false}:{detail?:boolean}) { return <section id="booking-lead-automation" className="booking-section"><div className="container booking-layout"><div className="booking-copy"><div className="eyebrow">BOOKING + LEAD AUTOMATION</div><h2 className="editorial">From “I’m interested”<br/>to <em>“you’re booked.”</em></h2><p className="description">One connected flow for your booking requests, client details, and follow-ups. So every potential client gets a thoughtful next step—even when you’re busy.</p><ul className="check-list"><li><Check/>Booking requests captured in one place</li><li><Check/>Lead details added automatically</li><li><Check/>Follow-ups that keep things moving</li><li><Check/>A clear view of who’s ready to book</li></ul><Button variant="editorial" className="cta-button" asChild>{detail?<a href="https://thelaunchera.com/pay/booking-flow/">Get Started <ArrowRight/></a>:<Link to="/booking-lead-automation">Meet your new booking flow <ArrowRight/></Link>}</Button></div><LeadTracker/></div></section> }
export function ProcessSection() { return <section className="process-section"><div className="container"><div className="section-heading"><div className="eyebrow">SIMPLE TO START. BUILT AROUND YOU.</div><h2 className="editorial">A better flow, in three steps.</h2></div><div className="process-grid"><div className="process-step"><div className="process-number">01</div><h3>Tell us what’s getting messy.</h3><p>We get to know your business, your current process, and what’s taking too much of your time.</p></div><div className="process-step"><div className="process-number">02</div><h3>We connect the dots.</h3><p>We build a thoughtful system around how you work—not a one-size-fits-all setup.</p></div><div className="process-step"><div className="process-number">03</div><h3>You get your time back.</h3><p>We walk you through your new flow, so you can step into your next era with confidence.</p></div></div></div></section> }
export function FinalCTA() { return <section className="final-section"><Wave/><div className="eyebrow">YOUR NEXT ERA STARTS HERE.</div><h2 className="editorial">A business that runs smoother.<br/><em>A day that feels lighter.</em></h2><p>Let’s take the scattered, time-consuming parts off your plate—and make room for what’s next.</p><Button variant="editorial" className="cta-button" asChild><Link to="/help"><MessageCircle/>Let’s talk about your business <ArrowUpRight/></Link></Button><div className="final-note">A simple inquiry. A thoughtful conversation. No pressure.</div></section> }
export function PageIntro({label,title,description}:{label:string,title:string,description:string}) { return <section className="page-intro"><div className="eyebrow">{label}</div><h1 className="editorial">{title}</h1><p>{description}</p></section> }
export function ContactForm() {
 const [ready,setReady]=useState(false);
 const [name,setName]=useState('');
 return <div className="contact-form">{ready?<div className="form-confirm"><Sparkles size={30}/><h3 className="editorial">A fresh start sounds good, {name.split(' ')[0]}.</h3><p>Your inquiry is ready to review. This standalone concept isn’t connected to a delivery service yet, so no message has been sent.</p><Button variant="outline" onClick={()=>setReady(false)}>Back to your inquiry <ArrowRight/></Button></div>:<><h2 className="editorial">Tell us about your business.</h2><p>A few details to start a thoughtful conversation.</p><form onSubmit={e=>{e.preventDefault();setReady(true)}}><div className="form-grid"><label className="field">Your name<input name="name" autoComplete="name" required value={name} onChange={e=>setName(e.target.value)} placeholder="First & last name"/></label><label className="field">Email address<input name="email" type="email" autoComplete="email" required placeholder="Where we can reach you"/></label></div><label className="field">Business name<input name="business" autoComplete="organization" required placeholder="Your cleaning business"/></label><label className="field">What can we help with?<select name="service" defaultValue="Booking + Lead Automation">{services.map(s=><option key={s.title}>{s.title}</option>)}<option>I’m not sure yet</option></select></label><label className="field">What’s taking up too much of your time?<textarea name="message" required placeholder="Tell us a little about your day-to-day…"/></label><Button type="submit" variant="editorial" className="cta-button">Review my inquiry <ArrowRight/></Button><p className="form-disclaimer">Concept preview: this form does not send inquiries yet.</p></form></>}</div>
}
export function HelpContent() { return <div className="container help-layout"><div className="faq-list"><h2 className="editorial">A little clarity, before we start.</h2><details><summary>Is this built for my kind of business?</summary><p>THE LAUNCH ERA is designed for U.S. residential cleaning business owners. Whether you’re managing inquiries yourself or growing a team, the goal is a simpler behind-the-scenes flow.</p></details><details><summary>Do I need to replace the tools I already use?</summary><p>Not necessarily. We start with your current process and look at what can connect, what can be simplified, and where a new tool would genuinely help.</p></details><details><summary>What does Booking + Lead Automation include?</summary><p>A connected booking inquiry flow, an organized Lead Tracker, and thoughtful follow-ups. Your setup is shaped around your business and how you bring on new clients.</p></details><details><summary>Can you help with more than bookings?</summary><p>Yes. Cleaning Web App, Website Automation, and Virtual Assistant support can help with other time-consuming parts of running your business.</p></details><details><summary>How much does it cost?</summary><p>We’ll first understand your needs, then share the scope and pricing before you make a commitment. No one-size-fits-all package or surprise costs.</p></details></div><ContactForm/></div> }